name: booster
description: The adjusted template for a new flutter project.

publish_to: 'none'
version: 2.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: 1.22.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.16.1
  injectable: ^1.0.4
  auto_route: ^0.6.7
  supercharged: ^1.10.0
  dart_extensions: ^1.0.1
  freezed_annotation: ^0.12.0
  json_annotation: ^3.1.1
  dartz: ^0.9.2

  bloc: ^6.1.0
  hydrated_bloc: ^6.1.0
  flutter_bloc: ^6.1.1
  logger: ^0.9.2
  pretty_dio_logger: ^1.1.1
  retrofit: ^1.3.4

  cupertino_icons: ^0.1.3
  cached_network_image: ^2.3.2+1
  # equatable is used inside design system due to
  # code generation for that slows down the implementation of the layout.
  equatable: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.4
  mockito: ^4.1.3

  build_runner: any
  injectable_generator: any
  auto_route_generator: ^0.6.8
  json_serializable: ^3.4.1
  freezed: ^0.12.1
  retrofit_generator: any

flutter:
  # Includes the Material Icons font.
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/config/localization/arb
  output_dir: lib/config/localization/generated
  use_deferred_loading: false
